### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by mianzg** [ds4owd-001/project-Dominiclemus#5]
@Dominiclemus 

Congrats again on accomplishing your capstone project! We are happy that you went through the course with us and applied the skills in the project.

I am reviewing your project on "SOLID WASTE GENERATION". Note that my review does not have any assessment on the writing content of the report, but I did enjoy reading it and learnt new stuff.

Please find the detailed feedback in the next section.

**Comment by mianzg** [comment]
Awesome! You have completed most of the required items in the [Required Items](https://ds4owd-001.github.io/website/project/#required-items). 

Some suggestions are
**Technical**
1. Use function `across` when you apply the same function on multiple columns when mutating. For example, the following code in line 73-78:
```{r}
dominic_processed <- dominic_processed_1 |> 
  mutate(food_organic_waste = as.numeric(food_organic_waste),
         glass = as.numeric(glass),
         metal = as.numeric(metal),
         other = as.numeric(other),
         paper_cardboard = as.numeric(paper_cardboard),
         plastic = as.numeric(plastic))
```
can be simplified to:
```{r}
Dominic_processed <- dominic_processed_1 |>
  mutate(across(c(food_organic_waste, glass, metal, other, paper_cardboard, plastic), as.numeric))
```
2. Consider to modify legend labels to be more human readable

**Data**
Is this a compilation of data from different sources via personal efforts? Please update README.md in `data/processed` to mention all data sources.

**Intellectural**
1. Give Table1 a caption about what unit these numbers are, are they proportions? are they weights in kg?
2. Combine Table 2 and 3 into a single table since they are summary statistics on the same variables.

**Comment by mianzg** [comment]
@Dominiclemus Furthermore, if this is an original dataset, we would like to have your project and data turning into an openwashdata data package! That means, we will develop an R data package that you will be an author. You and others can directly use a tidy version of the data in R later. Please let us know if you are interested in this! @margauxgo @larnsce

**Comment by Dominiclemus** [comment]
Hi Mian
I trust you're well
The data set that I used was downloaded from the World Bank data portals so
I don't consider it my original dataset. And what I haven't understood is
if I am to redo the project to collect the mistakes.
Thank you very much for the guidance and feedback provided.
Regards
Dominic Bagumaho

**Comment by mianzg** [comment]
@Dominiclemus Hello, you don't need to redo the project! We are out of capacities currently so we will send the certificates to all students when we are ready. Please be patient with us. Thank you!

 If you like to work on it, we are more than happy.
